name: Build 3

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
  workflow_run:
    workflows: [ "Multiple Build Queue" ]
    types:
      - completed

concurrency:
  group: sauce-queue
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set Environment Secret
      id: set_env
      run: |
        echo "SAUCE_USERNAME=${{ secrets.TEAM5_USERNAME }}" >> $GITHUB_ENV
        echo "SAUCE_ACCESS_KEY=${{ secrets.TEAM5_ACCESS_KEY }}" >> $GITHUB_ENV
    - name: Run Demo
      run: mvn test -Dsurefire.parallel=50
