name: Concurrency Tests

on:
  workflow_dispatch:
    inputs:
      parallel:
        description: "Parallel"
        default: "50"
      duration:
        description: "Duration"
        default: "15"
      team:
        description: "Team"
        required: true
        type: choice
        default: "Team 1"
        options:
          - Team 3
          - Team 5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set Environment Secret
      id: set_env
      run: |
        if [[ "${{ github.event.inputs.environment }}" == "Team 3" ]]; then
          echo "SAUCE_USERNAME=${{ secrets.TEAM3_USERNAME }}" >> $GITHUB_ENV
          echo "SAUCE_ACCESS_KEY=${{ secrets.TEAM3_ACCESS_KEY }}" >> $GITHUB_ENV
        elif [[ "${{ github.event.inputs.environment }}" == "Team 5" ]]; then
          echo "SAUCE_USERNAME=${{ secrets.TEAM5_USERNAME }}" >> $GITHUB_ENV
          echo "SAUCE_ACCESS_KEY=${{ secrets.TEAM5_ACCESS_KEY }}" >> $GITHUB_ENV
        fi
    - name: Run Demo
      run: mvn test -Dsurefire.parallel=${{ github.event.inputs.parallel }} -Dtest.duration=${{ github.event.inputs.duration }}
