name: Multiple Teams Limited
# This demonstrates limiting on flex accounts

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger other workflows
        run: echo "Run team2.yml, team3.yml; Team concurrency adds up to Org concurrency"
