name: Multiple Teams Simultaneously
# This demonstrates flexing on flex accounts

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger other workflows
        run: echo "Main workflow completed. Triggering other workflows."
