name: Multiple Teams Max Throughput

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger other workflows
        run: echo "Run team1-max.yml, team3-max.yml, team5-max.yml."
