name: Multiple Builds

on:
  workflow_dispatch:

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set Environment Secret
        id: set_env
        run: |
          echo "SAUCE_USERNAME=${{ secrets.TEAM5_USERNAME }}" >> $GITHUB_ENV
          echo "SAUCE_ACCESS_KEY=${{ secrets.TEAM5_ACCESS_KEY }}" >> $GITHUB_ENV
      - name: Run Build 1
        run: mvn test -Dsurefire.parallel=25 -Dbuild.name=Build1
  build2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set Environment Secret
        id: set_env
        run: |
          echo "SAUCE_USERNAME=${{ secrets.TEAM5_USERNAME }}" >> $GITHUB_ENV
          echo "SAUCE_ACCESS_KEY=${{ secrets.TEAM5_ACCESS_KEY }}" >> $GITHUB_ENV
      - name: Run Build 2
        run: mvn test -Dsurefire.parallel=25 -Dbuild.name=Build2

